version: "3.8"

services:
  backend:
    build: server
    ports:
      - "8080:8080"
    environment:
      - DB_URL= jdbc:postgresql://localhost:5432/Licenta

  frontend:
    build: frontend
    ports:
      - "3000:3080"
    depends_on:
      - backend