spring:
  profiles:
    active: dev
#    database connection details
  datasource:
    url: jdbc:postgresql://localhost:5432/chessopenings
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: vladdumitru46@yahoo.com
    password: blrqbnkwmidajgxz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000


custom:
  numberOfThreads: 4
  depthForAi: 3
  emailFrom: vladdumitru46@yahoo.com
